# Generated by Django 4.1.4 on 2023-01-06 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azad", "0005_alter_achievements_date_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 6, 15, 33, 45, 422923)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 6, 15, 33, 45, 420684)
            ),
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 6, 15, 33, 45, 421633)
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 6, 15, 33, 45, 422507)
            ),
        ),
        migrations.AlterField(
            model_name="para",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 6, 15, 33, 45, 421174)
            ),
        ),
    ]
