# Generated by Django 4.1.7 on 2023-02-21 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azad", "0009_merge_20230221_1827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 2, 21, 18, 27, 56, 445605)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 21, 18, 27, 56, 445605)
            ),
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 21, 18, 27, 56, 445605)
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 2, 21, 18, 27, 56, 445605)
            ),
        ),
        migrations.AlterField(
            model_name="para",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 21, 18, 27, 56, 445605)
            ),
        ),
    ]
