# Generated by Django 4.2.5 on 2023-10-17 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0033_alter_achievements_date_alter_complaints_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='manager_review',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 11, 10, 39, 715884)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='modified_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 11, 10, 39, 715884)),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 11, 10, 39, 715884)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 11, 10, 39, 715884)),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 11, 10, 39, 715884)),
        ),
    ]
