# Generated by Django 4.2.5 on 2023-10-17 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0034_complaints_manager_review_alter_achievements_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='image',
            field=models.ImageField(null=True, upload_to='azad_website/azad/static/assets/images/complain/'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 14, 23, 37, 74411)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 14, 23, 37, 64864)),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 14, 23, 37, 74411)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 14, 23, 37, 74411)),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 14, 23, 37, 74411)),
        ),
    ]
