# Generated by Django 4.2.5 on 2023-10-17 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0035_complaints_image_alter_achievements_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 14, 35, 44, 486068)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='image',
            field=models.ImageField(null=True, upload_to='static/assets/images/complain/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 14, 35, 44, 485871)),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 14, 35, 44, 486068)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 14, 35, 44, 486068)),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 14, 35, 44, 486068)),
        ),
    ]
