# Generated by Django 4.1.4 on 2024-01-07 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0054_alter_achievements_date_alter_azad_boarders_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 17, 51, 26, 977080)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 17, 51, 26, 977080)),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='static/images/logo/logo.svg', upload_to='event_images'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 17, 51, 26, 977080)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 17, 51, 26, 977080)),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 17, 51, 26, 977080)),
        ),
    ]
