# Generated by Django 4.1.4 on 2024-01-07 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0055_alter_achievements_date_alter_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='image',
        ),
        migrations.AddField(
            model_name='complaints',
            name='image_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 19, 40, 38, 38000)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 19, 40, 38, 38000)),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 19, 40, 38, 38000)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 19, 40, 38, 38000)),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 19, 40, 38, 38000)),
        ),
    ]
