# Generated by Django 4.1.4 on 2024-01-29 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0067_alter_achievements_date_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 29, 16, 50, 45, 579264)),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='subtitle',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='title',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='azad_boarders',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='department',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='created_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='modified_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='coveritem',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 16, 50, 45, 577557)),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='caption',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 16, 50, 45, 578317)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 29, 16, 50, 45, 578953)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='subtitle',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 16, 50, 45, 577969)),
        ),
        migrations.AlterField(
            model_name='requestedbook',
            name='author',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requestedbook',
            name='created_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requestedbook',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requestedbook',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requestedbook',
            name='studentName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requestedbook',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='dept',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=2500),
        ),
    ]
