# Generated by Django 4.1.4 on 2024-01-30 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0069_alter_achievements_date_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 30, 13, 59, 26, 514241)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 13, 59, 26, 512455)),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 13, 59, 26, 513203)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 30, 13, 59, 26, 513921)),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 13, 59, 26, 512819)),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='azad_book_title_adb6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='azad_book_author_b1aa99_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['department'], name='azad_book_departm_a08b54_idx'),
        ),
    ]
