# Generated by Django 4.1.4 on 2025-01-10 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0082_alter_achievements_date_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azad_boarders',
            name='role',
            field=models.CharField(default='user', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 10, 11, 53, 58, 289011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 11, 53, 58, 289011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 11, 53, 58, 289011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 10, 11, 53, 58, 289011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 11, 53, 58, 289011, tzinfo=datetime.timezone.utc)),
        ),
    ]
