# Generated by Django 4.1.4 on 2025-01-11 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0084_alter_achievements_date_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 11, 10, 20, 11, 163281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='azad_boarders',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='azad_boarders',
            name='roll_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 10, 20, 11, 163281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 10, 20, 11, 163281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 11, 10, 20, 11, 163281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 10, 20, 11, 163281, tzinfo=datetime.timezone.utc)),
        ),
    ]
