# Generated by Django 4.1.7 on 2023-02-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("azad", "0005_auto_20230109_1050"),
        ("azad", "0008_alter_achievements_date_alter_event_date_and_more"),
    ]

    operations = []
