# Generated by Django 4.1.7 on 2023-02-21 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azad", "0010_alter_achievements_date_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 2, 21, 18, 28, 0, 994093)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 21, 18, 28, 0, 994093)
            ),
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 21, 18, 28, 0, 994093)
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 2, 21, 18, 28, 0, 994093)
            ),
        ),
        migrations.AlterField(
            model_name="para",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 21, 18, 28, 0, 994093)
            ),
        ),
    ]
