# Generated by Django 4.1.4 on 2023-12-23 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azad', '0049_alter_achievements_date_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azad_boarders',
            name='books',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 23, 11, 55, 5, 878216)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 11, 55, 5, 878216)),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 11, 55, 5, 878216)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 23, 11, 55, 5, 878216)),
        ),
        migrations.AlterField(
            model_name='para',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 11, 55, 5, 878216)),
        ),
    ]
